resources:
  - url: http://127.0.0.1:5000/uptime-card.js
    type: module

views:
  - cards:
      - type: custom:uptime-card
        name: Uptime Card Development
        entity: sun.sun
        test_gui: true
